export const AdropUnitId = {
    // Banner
    BANNER_IMAGE_320_50: 'PUBLIC_TEST_UNIT_ID_320_50',
    BANNER_IMAGE_375_80: 'PUBLIC_TEST_UNIT_ID_375_80',

    // Native
    NATIVE: 'PUBLIC_TEST_UNIT_ID_NATIVE',

    // Popup
    POPUP_BOTTOM: 'PUBLIC_TEST_UNIT_ID_POPUP_BOTTOM',
    POPUP_CENTER: 'PUBLIC_TEST_UNIT_ID_POPUP_CENTER',

    // Rewarded
    REWARDED: 'PUBLIC_TEST_UNIT_ID_REWARDED',

    // Interstitial
    INTERSTITIAL: 'PUBLIC_TEST_UNIT_ID_INTERSTITIAL',
} as const
