export enum AdropErrorCode {
    network = 'ERROR_CODE_NETWORK',
    internal = 'ERROR_CODE_INTERNAL',
    initialize = 'ERROR_CODE_INITIALIZE',
    invalidUnit = 'ERROR_CODE_INVALID_UNIT',
    notTargetCountry = 'ERROR_CODE_NOT_TARGET_COUNTRY',
    inactive = 'ERROR_CODE_AD_INACTIVE',
    adNoFill = 'ERROR_CODE_AD_NO_FILL',
    adDuplicated = 'ERROR_CODE_AD_LOAD_DUPLICATED',
    adLoading = 'ERROR_CODE_AD_LOADING',
    adEmpty = 'ERROR_CODE_AD_EMPTY',
    adShown = 'ERROR_CODE_AD_SHOWN',
    adHideForToday = 'ERROR_CODE_AD_HIDE_FOR_TODAY',
    adLandscapeUnsupported = 'ERROR_CODE_LANDSCAPE_UNSUPPORTED',
    backfillNoFill = 'ERROR_CODE_AD_BACKFILL_NO_FILL',
    undefined = 'UNDEFINED',
}
